# for header
species: 41

# time settings
times_from_file: false
times_file_path: ""
times: [["20150101", "000000", "20150101", "000001"]] # will be ignored if read_from_file: true

# for height profile
column_mode: "pressure_full" # "pressure_pure" "pressure_wu"
regions: [0, 3, 6]
dh: [100, 500]
lowest_region_n: 3000
discrete: false

# positions of stations
coords_from_file: false
coords_file_path: ""
coords: [[1,2,3,4]] # will be ignored if read_from_file: true

# other settings
zkind: 1
mass: 1