# for header
species: 41

# time settings
times_from_file: false
times_file_path: ""
times: [["20091130", "195959", "20091130", "200000"], ["20091130", "195959", "20091130", "200000"]] # will be ignored if read_from_file: true

# for height profile
column_mode: "unit" # "pressure_pure" "pressure_wu"
height_low: 0
height_up: 21 # in km
dh: 500 # in meters
n_total: 40000
discrete: false

# positions of stations
coords_from_file: false
coords_file_path: ""
coords: [[150.878998,150.878998,-34.4059982,-34.4059982], [130.891693,130.891693,-12.4245996,-12.4245996]] # will be ignored if read_from_file: true

# other settings
zkind: 1
mass: 1.0
