# for header
species: 41

# time settings
times_from_file: false
times_file_path: ""
times: [["20091207", "205959", "20091207", "210000"]] # will be ignored if read_from_file: true

# for height profile
column_mode: "pressure_wu" # "pressure_pure" "pressure_wu"
regions: [0, 3, 6]
dh: [100, 500]
region_n: [3334, 667]
discrete: false

# positions of stations
coords_from_file: false
coords_file_path: ""
coords: [[130.891693,130.891693,-12.4245996,-12.4245996]] # will be ignored if read_from_file: true

# other settings
zkind: 1
mass: 1
